# ourAgentTeams configuration — generated by setup wizard
# Re-run `ouragentteams init --force` to regenerate.
leader:
  model: qwen2.5:7b
  provider: ollama
  ollama_base_url: http://127.0.0.1:11434
  fallbacks: []
  heartbeat_interval_s: 5
  watchdog_timeout_s: 30
workers:
  local: []
  api: []
monitor:
  heartbeat_interval_s: 10
  timeout_threshold_s: 120
  max_retries: 3
cost:
  monthly_budget_usd: 20.0
  importance_threshold_local: 5
  importance_threshold_best: 8
privacy:
  enabled: true
  mode: "balanced"  # strict | balanced | disabled
  entities:
  - PERSON
  - EMAIL_ADDRESS
  - PHONE_NUMBER
  - CREDIT_CARD
  - API_KEY
  - PASSWORD
