# ourAgentTeams — Environment Variables
# Generated by setup wizard. Add or remove keys as needed.
# This file should be chmod 600 and NEVER committed to version control.

# ── Cloud API Keys ───────────────────────────────────────────────────────────

# OpenAI (gpt-4o, gpt-4o-mini, etc.)
# OPENAI_API_KEY=

# Anthropic (claude-3-5-sonnet, etc.)
# ANTHROPIC_API_KEY=

# Google (gemini-1.5-pro, etc.)
# GOOGLE_API_KEY=

# Mistral
# MISTRAL_API_KEY=

# Cohere
# COHERE_API_KEY=

# DeepSeek (cloud API, separate from local Ollama)
# DEEPSEEK_API_KEY=

# Azure OpenAI
# AZURE_OPENAI_API_KEY=
# AZURE_API_BASE=https://your-resource.openai.azure.com/
# AZURE_API_VERSION=2024-02-01

# ── Optional knobs ───────────────────────────────────────────────────────────
# OURAGENTTEAMS_DISABLE_RAG=1   # disable Chroma RAG (offline / SSL issues)
